spring.application.name=SwitchPagos
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/switch_banquito
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none


