spring.application.name=SwitchPagos
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# Database Configuration
spring.datasource.url=jdbc:postgresql://34.27.240.236:5432/banquito_switch
spring.datasource.username=admin
spring.datasource.password=banbanquito2
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none

# SFTP Configuration
sftp.port=2222
sftp.root-path=./sftp-data
sftp.username=banquito
sftp.password=banquito123

# Mail Configuration
spring.mail.host=34.27.240.236
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Mailpit API Configuration
mailpit.api.url=http://34.27.240.236:8025/api/v1
